# The manifest for the "web" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: web
type: Load Balanced Web Service

# Distribute traffic to your service.
http:
  # Requests to this path will be forwarded to your service.
  # To match all requests you can use the "/" path.
  path: "/"
  # You can specify a custom health check path. The default is "/".
  healthcheck: "/healthcheck"

# Configuration for your containers and service.
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build
  build:
    dockerfile: ../appcontainer/Dockerfile
    context: ../
  # Port exposed through your container to route traffic to it.
  port: 8000

cpu: 256 # Number of CPU units for the task.
memory: 512 # Amount of memory in MiB used by the task.
platform: linux/x86_64 # See https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#platform
count: 1 # Number of tasks that should be running in your service.
exec: true # Enable running commands in your container.
command: bin/start_aws.sh
network:
  connect: true # Enable Service Connect for intra-environment traffic between services.
  vpc:
    security_groups:
      - from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-postgresSecurityGroup
# storage:
# readonly_fs: true       # Limit to read-only access to mounted root filesystems.

# Optional fields for more advanced use-cases.
#
variables: # Pass environment variables as key value pairs.
  STREAMLIT_URL: /streamlit
  BUCKET_NAME:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-s3webBucketName

secrets: # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
  DJANGO_ALLOWED_HOSTS: /pems/web/${COPILOT_ENVIRONMENT_NAME}/DJANGO_ALLOWED_HOSTS
  DJANGO_DB_NAME: /pems/web/${COPILOT_ENVIRONMENT_NAME}/DJANGO_DB_NAME
  DJANGO_DB_USER: /pems/web/${COPILOT_ENVIRONMENT_NAME}/DJANGO_DB_USER
  DJANGO_DB_PASSWORD: /pems/web/${COPILOT_ENVIRONMENT_NAME}/DJANGO_DB_PASSWORD
  DJANGO_DB_FIXTURES: /pems/web/${COPILOT_ENVIRONMENT_NAME}/DJANGO_DB_FIXTURES
  POSTGRES_SECRET:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-postgresAuroraSecret
# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
#    deployment:            # The deployment strategy for the "test" environment.
#       rolling: 'recreate' # Stops existing tasks before new ones are started for faster deployments.
