name: pems

services:
  app:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: caltrans/pems:app
    env_file: .env
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: caltrans/pems:dev
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    volumes:
      - ./:/caltrans/app

  docs:
    image: caltrans/pems:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ./:/caltrans/app
