name: pems

services:
  web:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: caltrans/pems:web
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: caltrans/pems:dev
    depends_on:
      - postgres
      - pgweb
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    volumes:
      - ./:/caltrans/app
      - ${HOME}/.aws:/home/caltrans/.aws

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT:-8081}:8081"
    depends_on:
      - postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable

  docs:
    image: caltrans/pems:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ./:/caltrans/app

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    image: caltrans/pems:streamlit
    env_file: .env
    ports:
      - "${STREAMLIT_LOCAL_PORT:-8501}:8501"
    volumes:
      - ./:/caltrans/app

volumes:
  pgdata:
    driver: local
