site_name: "caltrans/pems: Documentation"
repo_url: https://github.com/compilerla/pems
edit_uri: edit/main/docs
site_url: https://compilerla.github.io/pems

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
  palette:
    scheme: default

extra:
  analytics:
    provider: google
    property: G-xxxxxxxxxx

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - redirects:
      redirect_maps:

extra_css:
  - https://use.fontawesome.com/releases/v6.1.2/css/all.css
  - styles/theme.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - mdx_truly_sane_lists
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
