# Generated by Django 5.2.3 on 2025-07-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataCatalog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(help_text="The name of this data catalog.")),
                ("slug", models.SlugField(help_text="The unique slug for this data catalog.", unique=True)),
            ],
            options={
                "verbose_name": "Data Catalog",
                "verbose_name_plural": "Data Catalogs",
            },
        ),
        migrations.CreateModel(
            name="CatalogEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(help_text="The name of this catalog entry.")),
                ("slug", models.SlugField(help_text="The unique slug for this catalog entry.", unique=True)),
                ("catalogs", models.ManyToManyField(to="clearinghouse.datacatalog")),
            ],
            options={
                "verbose_name": "Catalog Entry",
                "verbose_name_plural": "Catalog Entries",
            },
        ),
    ]
