name: Label actions

on:
  pull_request:
    types: [opened]
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/**"

jobs:
  label-actions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add-label
        uses: andymckay/labeler@master
        with:
          add-labels: "actions"
